require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const path = require('path');
const cors = require('cors');
const nodemailer = require('nodemailer');
const PDFDocument = require('pdfkit');
const { PassThrough } = require('stream');
const fs = require('fs');
const bcrypt = require('bcrypt');
const pool = require('./db');

// Routers for CRUD endpoints
const itemsRouter = require('./routes/items');
const modelsRouter = require('./routes/models');
const unitsRouter = require('./routes/units');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, '..')));

// Register API routers so pages (items/models/units) can fetch data
app.use('/api/items', itemsRouter);
app.use('/api/models', modelsRouter);
app.use('/api/units', unitsRouter);

// Helper: generate PDF buffer for a leave application
async function createLeavePdf({ fullName, leaveType, fromDate, toDate, leaveremarks, submittedOn, leavenumberdays }) {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });
  const stream = new PassThrough();
  doc.pipe(stream);

  const pageWidth = doc.page.width;
  const mspLogoFile = path.join(__dirname, '..', 'assets', 'images', 'MSP_Logo-00.png');
  const deskHubLogoFile = path.join(__dirname, '..', 'assets', 'images', 'deskhub.png');

  // Adjust MSP logo position/size so its center aligns with the reference line in the mockup
  // Note: keep the DeskHub logo position unchanged
  if (fs.existsSync(mspLogoFile)) doc.image(mspLogoFile, 40, 2, { width: 140, height: 80 });
  if (fs.existsSync(deskHubLogoFile)) doc.image(deskHubLogoFile, pageWidth - 40 - 113, 20, { width: 113, height: 28 });

  doc
    .font('Helvetica-Bold')
    .fontSize(12)
    .text('MONITORING SOLUTION PROVIDERS PTE LTD', 0, 75, { align: 'center' })
    .font('Helvetica')
    .fontSize(9)
    .text('33 Ubi Ave 3, Vertex #05-31 Tower B, Singapore 408868', { align: 'center' })
    .text('Office : +65 6747 9766  |  Fax : +65 6458 0824  |  Website: www.mspsystem.com', { align: 'center' })
    .moveDown(1);

  doc
    .font('Helvetica-Bold')
    .fontSize(16)
    .text('LEAVE APPLICATION FORM', { align: 'center', underline: true })
    .moveDown(1.2);

  // Details box
  const boxX = 50;
  const boxY = doc.y;
  const boxW = doc.page.width - boxX * 2;

  doc.rect(boxX, boxY, boxW, 180).stroke();

  const boxLabelX = boxX + 15;
  const boxValueX = boxX + 160;
  let y2 = boxY + 12;

  const putRow = (label, value) => {
    doc.font('Helvetica-Bold').fontSize(10).text(label, boxLabelX, y2);
    doc.font('Helvetica').fontSize(10).text(`: ${value || 'N/A'}`, boxValueX, y2);
    y2 += 20;
  };

  putRow('Full Name', fullName);
  putRow('Leave Type', leaveType);
  putRow('Submitted On', submittedOn);
  putRow('From Date', fromDate);
  putRow('To Date', toDate);
  putRow('Number of Days', leavenumberdays);

  doc.font('Helvetica-Bold').fontSize(10).text('Remarks', boxLabelX, y2);
  doc.font('Helvetica').fontSize(10).text(leaveremarks || 'N/A', boxValueX, y2, { width: boxW - (boxValueX - boxX) - 20 });

  doc.y = boxY + 180 + 20;

  const sigY = doc.y + 20;
  const sigW = (doc.page.width - 100) / 2;
  const sig1X = 50;
  const sig2X = sig1X + sigW + 20;

  doc.moveDown(3);
  doc.moveTo(sig1X, sigY).lineTo(sig1X + sigW - 20, sigY).stroke();
  doc.font('Helvetica').fontSize(10).text('Employee Signature', sig1X, sigY + 5);

  doc.moveTo(sig2X, sigY).lineTo(sig2X + sigW - 20, sigY).stroke();
  doc.font('Helvetica').fontSize(10).text('Approved By', sig2X, sigY + 5);


  // Footer: anchor at bottom center of the page
  const footerText = 'Generated by Monitoring Solution Providers Pte. Ltd.\n(DeskHub Portal)';
  doc.font('Helvetica').fontSize(9).fillColor('gray').text(footerText, 0, doc.page.height - 65, { align: 'center', width: pageWidth });

    doc.end();

  const buffer = await new Promise((resolve, reject) => {
    const chunks = [];
    stream.on('data', chunk => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
  });

  return buffer;
}

app.post('/api/login', async (req, res) => {
  const { username, password } = req.body;
  try {
    const result = await pool.query("SELECT * FROM users WHERE username = $1", [username]);
    if (result.rows.length === 0) return res.status(401).json({ message: "Invalid username or password." });
    const user = result.rows[0];
    const match = await bcrypt.compare(password, user.password_hash);
    if (!match) return res.status(401).json({ message: "Invalid username or password." });
    res.status(200).json({ message: "Login successful." });
  } catch (err) {
    console.error("Login error:", err);
    res.status(500).json({ message: "Server error." });
  }
});

app.get('/api/send-leave-pdf', (req, res) => {
  // Informative response for browser GETs (avoids default "Cannot GET" page)
  return res.status(405).json({ message: 'This endpoint accepts POST requests only. Submit the leave form to POST JSON to /api/send-leave-pdf.' });
});

// Simple logout endpoint (client-side also clears localStorage)
app.post('/logout', (req, res) => {
  // If you add server-side sessions later, clear them here
  return res.status(200).json({ message: 'Logged out' });
});

app.post('/api/send-leave-pdf', async (req, res) => {
  // Debug logging: helps diagnose why submissions fail (remove in production)
  console.log('POST /api/send-leave-pdf received');
  console.log('Request body preview:', {
    fullName: req.body && req.body.fullName,
    leaveType: req.body && req.body.leaveType,
    fromDate: req.body && req.body.fromDate,
    toDate: req.body && req.body.toDate
  });

  const {
    fullName,
    leaveType,
    fromDate,
    toDate,
    leaveremarks,
    submittedOn,
    leavenumberdays
  } = req.body;

  const recipient = process.env.EMAIL_TO;

  try {
    const pdfBuffer = await createLeavePdf({ fullName, leaveType, fromDate, toDate, leaveremarks, submittedOn, leavenumberdays });

    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST,
      port: parseInt(process.env.EMAIL_PORT),
      secure: process.env.EMAIL_SECURE === 'true',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      },
      tls: { rejectUnauthorized: false }
    });

    await transporter.sendMail({
      from: `"DeskHub" <${process.env.EMAIL_USER}>`,
      to: recipient,
      subject: `Deskhub Leave Application : ${fullName || ''}`,
      text: `Please find attached the leave application form for ${fullName || 'the applicant'}.`,
      attachments: [
        { filename: `${(fullName || 'applicant').replace(/\s+/g, '_')}-leave-application.pdf`, content: pdfBuffer }
      ]
    });

    res.status(200).json({ message: 'Email sent successfully!' });

  } catch (error) {
    console.error('Error generating/sending PDF:');
    console.error(error && error.stack ? error.stack : error);
    // Send a more informative error for debugging (remove error details in production)
    res.status(500).json({ message: 'Failed to send email.', error: (error && error.message) || String(error) });
  }
});

app.listen(PORT, () => console.log(`✅ Server running on http://localhost:${PORT}`));
console.log('PDF generated. Preparing to send email...');

