require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const path = require('path');
const bcrypt = require('bcrypt');
const pool = require('./db');
const cors = require('cors');
const nodemailer = require('nodemailer');
const PDFDocument = require('pdfkit');
const { PassThrough } = require('stream');

const unitsRouter = require('./routes/units');
const modelsRouter = require('./routes/models');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, "..")));

app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "..", "login.html"));
});

app.post('/api/login', async (req, res) => {
  const { username, password } = req.body;

  try {
    const result = await pool.query("SELECT * FROM users WHERE username = $1", [username]);
    if (result.rows.length === 0) return res.status(401).json({ message: "Invalid username or password." });

    const user = result.rows[0];
    const match = await bcrypt.compare(password, user.password_hash);
    if (!match) return res.status(401).json({ message: "Invalid username or password." });

    res.status(200).json({ message: "Login successful." });
  } catch (err) {
    console.error("Login error:", err);
    res.status(500).json({ message: "Server error." });
  }
});

app.post('/api/send-leave-pdf', async (req, res) => {
  const { fullName, leaveType, fromDate, toDate, reason, submittedOn } = req.body;
  const recipient = process.env.EMAIL_TO;

  try {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    doc.pipe(stream);

    // Logo path
    const logoPath = path.join(__dirname, '..', 'assets', 'images', 'deskhub.png');

    // Header with logo
    try {
      doc.image(logoPath, 50, 45, { width: 60 });
    } catch (err) {
      console.warn('⚠️ Logo not found at', logoPath);
    }

    doc.fontSize(20).text("DeskHub Leave Application", 0, 50, {
      align: 'center'
    });

    doc.moveDown(2);

    doc.fontSize(12);
    doc.text(`Full Name:     ${fullName}`);
    doc.text(`Leave Type:    ${leaveType}`);
    doc.text(`From Date:     ${fromDate}`);
    doc.text(`To Date:       ${toDate}`);
    doc.text(`Reason:        ${reason || "N/A"}`);
    doc.text(`Submitted On:  ${submittedOn}`);

    doc.moveDown();
    doc.text('Signature: _______________________________', { lineGap: 10 });

    doc.moveDown();
    doc.fontSize(10).fillColor('gray').text('Generated by DeskHub System', { align: 'center' });

    doc.end();

    const pdfBuffer = await new Promise((resolve, reject) => {
      const chunks = [];
      stream.on("data", chunk => chunks.push(chunk));
      stream.on("end", () => resolve(Buffer.concat(chunks)));
      stream.on("error", reject);
    });

    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST,
      port: parseInt(process.env.EMAIL_PORT),
      secure: process.env.EMAIL_SECURE === 'true',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      },
      tls: { rejectUnauthorized: false }
    });

    await transporter.sendMail({
      from: `"DeskHub" <${process.env.EMAIL_USER}>`,
      to: recipient,
      subject: "📧 Leave Application",
      text: "Attached is the generated leave application PDF.",
      attachments: [{
        filename: 'leave-application.pdf',
        content: pdfBuffer
      }]
    });

    res.status(200).json({ message: "Email sent successfully!" });

  } catch (error) {
    console.error("Error generating/sending PDF:", error);
    res.status(500).json({ message: "Failed to send email." });
  }
});

app.use('/api/items', require('./routes/items'));
app.use('/api/models', modelsRouter);
app.use('/api/units', unitsRouter);

app.use((req, res) => res.status(404).send("Page not found"));

app.listen(PORT, () => {
  console.log(`🚀 DeskHub server running at http://localhost:${PORT}`);
});
