require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const path = require('path');
const cors = require('cors');
const nodemailer = require('nodemailer');
const PDFDocument = require('pdfkit');
const { PassThrough } = require('stream');
const fs = require('fs');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, '..')));

app.post('/api/send-leave-pdf', async (req, res) => {
  const {
    fullName,
    leaveType,
    fromDate,
    toDate,
    leaveremarks,
    submittedOn,
    leavenumberdays, // ✅ FIXED comma error here
  } = req.body;

  const recipient = process.env.EMAIL_TO;

  try {
    const doc = new PDFDocument({ margin: 50 });
    const stream = new PassThrough();
    doc.pipe(stream);

    // Paths to logos
    const mspLogoPath = path.join(__dirname, '..', 'assets', 'images', 'MSP_Logo-00.png');
    const deskHubLogoPath = path.join(__dirname, '..', 'assets', 'images', 'deskhub.png');

    // MSP logo (left) 
    if (fs.existsSync(mspLogoPath)) {
      doc.image(mspLogoPath, 10, 0, { width: 170, height: 160 });
    }

    // DeskHub logo (right) - 1x4 cm (≈113x28 px)
    if (fs.existsSync(deskHubLogoPath)) {
      doc.image(deskHubLogoPath, doc.page.width - 50 - 113, 30, { width: 113, height: 28 });
    }

    // Company Info
    doc
      .fontSize(9)
      .text('MONITORING SOLUTION PROVIDERS PTE LTD', 50, 120)
      .text('33 Ubi Ave 3, Vertex #05-31 Tower B, Singapore 408868')
      .text('Office   : +65 6747 9766')
      .text('Fax      : +65 6458 0824')
      .text('Website  : www.mspsystem.com')
      .moveDown(2);

    // Title
    doc
      .fontSize(14)
      .text('LEAVE APPLICATION FORM', { align: 'center', underline: true })
      .moveDown(2);

    // Labels and values aligned
    const labelX = 70;
    const valueX = 200;

    doc.fontSize(11);
    doc.text('Full Name			:', labelX).text(fullName, valueX, doc.y);
    doc.moveDown();
    doc.text('Leave Type			:', labelX).text(leaveType, valueX, doc.y);
    doc.moveDown();
    doc.text('Submitted On			:', labelX).text(submittedOn, valueX, doc.y);
    doc.moveDown();
    doc.text('From Date			:', labelX).text(fromDate, valueX, doc.y);
    doc.moveDown();
    doc.text('To Date			:', labelX).text(toDate, valueX, doc.y);
    doc.moveDown();
    doc.text('Number of Days			:', labelX).text(leavenumberdays, valueX, doc.y);
    doc.moveDown();    
	
	doc.text('Remarks			:', labelX).text(leaveremarks || 'N/A', valueX, doc.y);
    doc.moveDown(3);

    // Approval
    doc.text('APPROVED BY:', labelX);
    doc.moveDown(2);
    doc.text('_______________________________', labelX);

    // Footer
    doc
      .moveDown(2)
      .fontSize(9)
      .fillColor('gray')
      .text('Generated by Monitoring Solution Providers Pte. Ltd. (DeskHub Portal)', { align: 'center' });

    doc.end();

    const pdfBuffer = await new Promise((resolve, reject) => {
      const chunks = [];
      stream.on('data', chunk => chunks.push(chunk));
      stream.on('end', () => resolve(Buffer.concat(chunks)));
      stream.on('error', reject);
    });

    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST,
      port: parseInt(process.env.EMAIL_PORT),
      secure: process.env.EMAIL_SECURE === 'true',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      },
      tls: { rejectUnauthorized: false }
    });

    await transporter.sendMail({
      from: `"DeskHub" <${process.env.EMAIL_USER}>`,
      to: recipient,
      subject: "Leave Application Form Submission",
      text: "Attached is the Leave Application PDF.",
      attachments: [
        { filename: 'leave-application.pdf', content: pdfBuffer }
      ]
    });

    res.status(200).json({ message: 'Email sent successfully!' });

  } catch (error) {
    console.error('Error generating/sending PDF:', error);
    res.status(500).json({ message: 'Failed to send email.' });
  }
});

app.listen(PORT, () => console.log(`✅ Server running on http://localhost:${PORT}`));
console.log('PDF generated. Preparing to send email...');

